# 2nd_lab

In [1]:
print("Hello, World!")

Hello, World!


In [2]:
a = input("Enter a Number: ")
print(a)

523


# Practice Session

* New to Python

In [8]:
import numpy as np

In [14]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])